# development:
#   adapter: mysql2
#   database: database_development
#   encoding: utf8
#   host: localhost
#   pool: 5
#   password:
#   reconnect: false
#   username: admin
#   timeout: 5000

# # add test/staging/production

development:
  adapter: postgresql
  encoding: unicode
  database: breeze-mapper_development
  pool: 5
  username: 
  password: 

test:
  adapter: postgresql
  encoding: unicode
  database: breeze-mapper_test
  pool: 5
  username: 
  password: 