development:
  adapter: postgresql
  encoding: unicode
  database: breeze-mapper_development
  pool: 5
  username: 
  password: 

test:
  adapter: postgresql
  encoding: unicode
  database: breeze-mapper_test
  pool: 5
  username: 
  password: 